#### Merge Layers

In [1]:
from tensorflow.keras.layers import Input, Add

in_tensor_1 = Input((1,))
in_tensor_2 = Input((1,))
added = Add()([in_tensor_1, in_tensor_2])

#### Create model

In [2]:
from tensorflow.keras import Model

model = Model(inputs=[in_tensor_1, in_tensor_2], outputs=added)

model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_1       │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 1)         │          0 │ input_layer[0][0… │
│                     │                   │            │ input_layer_1[0]… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Compile the model

In [4]:
model.compile(optimizer='adam', loss='mean_absolute_error')

In [ ]:
# Import the Subtract layer from tensorflow.keras
from tensorflow.keras.layers import Subtract

# Create a subtract layer using the inputs from the previous exercise
score_diff = Subtract()([team_1_strength, team_2_strength])

In [ ]:
# Imports
from tensorflow.keras.layers import Subtract
from tensorflow.keras.models import Model

# Subtraction layer from previous exercise
score_diff = Subtract()([team_1_strength, team_2_strength])

# Create the model
model = Model([team_in_1, team_in_2], score_diff)

# Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error')

#### Fit with Multiple input

In [ ]:
model.fit([data_1, data_2], targets)

#### Predict with multiple inputs

In [5]:
import numpy as np

model.predict([np.array([[1]]), np.array([[2]])])
np.array([[[3.]]], dtype=np.float32)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 412ms/step

array([[[3.]]], dtype=float32)

In [7]:
model.predict([np.array([[42]]), np.array([[119]])])
np.array([[[161.]]], dtype=np.float32)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

array([[[161.]]], dtype=float32)

#### Evaluate with multiple inputs

In [8]:
model.evaluate([np.array([[-1]]), np.array([[-2]])], np.array([[[-3.]]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 715ms/step - loss: 0.0000e+00

0.0

In [9]:
# Get the team_1 column from the regular season data
import numpy as np
input_1 = games_season['team_1']

# Get the team_2 column from the regular season data
input_2 = games_season['team_2']

# Fit the model to input 1 and 2, using score diff as a target
model.fit([np.array(input_1), np.array(input_2)],
          games_season['score_diff'],
          epochs=1,
          batch_size=2048,
          validation_split=0.1,
          verbose=True)

NameError: name 'games_season' is not defined

In [ ]:
# Get team_1 from the tournament data
input_1 = games_tourney['team_1']

# Get team_2 from the tournament data
input_2 = games_tourney['team_2']

# Evaluate the model using these inputs
print(model.evaluate([input_1, input_2], games_tourney['score_diff'], verbose=False))

#### Simple model with 3 inputs

In [10]:
from tensorflow.keras.layers import Dense, Layer, Input, Concatenate
in_tensor_1 = Input((1,))
in_tensor_2 = Input((1,))
in_tensor_3 = Input((1,))
concat = Concatenate()([in_tensor_1, in_tensor_2, in_tensor_3])
output_tensor = Dense(1)(concat)

In [11]:
from tensorflow.keras.models import Model
model = Model(inputs=[in_tensor_1, in_tensor_2, in_tensor_3], outputs=output_tensor)

#### Shared layers with 3 inputs

In [ ]:
shared_layer = Dense(1)
shared_layer_1 = shared_layer(in_tensor_1)
shared_layer_2 = shared_layer(in_tensor_2)
output_tensor =Concatenate()([shared_layer_1, shared_layer_2])
output_tensor = Dense(1)(output_tensor)
model = Model(inputs=[in_tensor_1, in_tensor_2, in_tensor_3], outputs=output_tensor)

#### Fitting a 3 input model

In [12]:
from tensorflow.keras.models import Model
model = Model(inputs=[in_tensor_1, in_tensor_2, in_tensor_3], outputs=output_tensor)
model.compile(loss='mae', optimizer='adam')

In [13]:
model.fit([train['col1'], train['col2'], train['col3']], train_data['target'])

NameError: name 'train' is not defined

In [ ]:
model.evaluate([[test['col1'], test['col2'], test['col3']], test['target']])

In [ ]:
# Create an Input for each team
team_in_1 = Input(shape=(1,), name='Team-1-In')
team_in_2 = Input(shape=(1,), name='Team-2-In')

# Create an input for home vs away
home_in = Input(shape=(1,), name='Home-In')

# Lookup the team inputs in the team strength model
team_1_strength = team_strength_model(team_in_1)
team_2_strength = team_strength_model(team_in_2)

# Combine the team strengths with the home input using a Concatenate layer, then add a Dense layer
out = Concatenate()([team_1_strength,team_2_strength, home_in])
out = Dense(1)(out)

In [ ]:
# Import the model class
from tensorflow.keras.models import Model

# Make a Model
model = Model([team_in_1, team_in_2, home_in],out)

# Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error')

In [ ]:
# Fit the model to the games_season dataset
model.fit([games_season['team_1'], games_season['team_2'], games_season['home']],
          games_season['score_diff'],
          epochs=1,
          verbose=1,
          validation_split=0.1,
          batch_size=2048)

# Evaluate the model on the games_tourney dataset
print(model.evaluate([games_tourney['team_1'], games_tourney['team_2'], games_tourney['home']],
                    games_tourney['score_diff'], verbose=False))

In [14]:
# Imports
import matplotlib.pyplot as plt
from tensorflow.keras.utils import plot_model

# Plot the model
plot_model(model, to_file='model.png')

# Display the image
data = plt.imread('model.png')
plt.imshow(data)
plt.show()

You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.

FileNotFoundError: [Errno 2] No such file or directory: 'model.png'

#### Stacking models

In [1]:
from pandas import read_csv
games_season = read_csv('games_season.csv')
games_season.head()

   season  team_1  team_2  home  score_diff  score_1  score_2  won
0    1985    3745    6664     0          17       81       64    1
1    1985     126    7493     1           7       77       70    1
2    1985     288    3593     1           7       63       56    1
3    1985    1846    9881     1          16       70       54    1
4    1985    2675   10298     1          12       86       74    1

In [2]:
games_tourney = read_csv('games_tourney.csv')
games_tourney.head()

   season  team_1  team_2  home  seed_diff  score_diff  score_1  score_2  won
0    1985     288      73     0         -3          -9       41       50    0
1    1985    5929      73     0          4           6       61       55    1
2    1985    9884      73     0          5          -4       59       63    0
3    1985      73     288     0          3           9       50       41    1
4    1985    3920     410     0          1          -9       54       63    0

#### Enrich the tournament data

In [4]:
in_data_1 = games_tourney['team_1']
in_data_2 = games_tourney['team_2']
in_data_3 = games_tourney['home']
pred = regular_season_model.predict([in_data_1, in_data_2], in_data_3)

NameError: name 'regular_season_model' is not defined

In [5]:
games_tourney['pred'] = pred
games_tourney.head()

NameError: name 'pred' is not defined

### 3 Input model with pure numeric data

In [6]:
from tensorflow.keras.layers import Input, Dense
in_tensor = Input(shape=(3, ))
out_tensor = Dense(1)(in_tensor)

In [7]:
from tensorflow.keras.models import Model
model = Model(inputs=in_tensor, outputs=out_tensor)
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 3)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4 (16.00 B)

 Trainable params: 4 (16.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='mean_absolute_error')
train_X = train_data[['home', 'seed_diff', 'pred']]
train_y = train_data['score_diff']
model.fit(train_X, train_y, epochs=10, validation_split=0.10)

In [ ]:
Test_X = test_data[['home', 'seed_diff', 'pred']]
Test_y = test_data['score_diff']
model.evaluate(Test_X, Test_y)

In [ ]:
# Predict
games_tourney['pred'] = model.predict([games_tourney['team_1'], games_tourney['team_2'], games_tourney['home']])

In [ ]:
# Create an input layer with 3 columns
input_tensor = Input((3,))

# Pass it to a Dense layer with 1 unit
output_tensor = Dense(1)(input_tensor)

# Create a model
model = Model(input_tensor, output_tensor)

# Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error')

In [ ]:
# Fit the model
model.fit(games_tourney_train[['home', 'seed_diff', 'pred']],
          games_tourney_train['score_diff'],
          epochs=1,
          verbose=True)

In [ ]:
# Evaluate the model on the games_tourney_test dataset
print(model.evaluate(games_tourney_test[['home', 'seed_diff', 'prediction']],
               games_tourney_test['score_diff'], verbose=False))